from dash_docs import chapter_index


def generate_sitemap():
    sitemap = ''
    for url in chapter_index.URL_TO_CONTENT_MAP:
        if url.startswith('/'):
            sitemap += (
                '<url>\n' +
                '    <loc>https://dash.plot.ly{}</loc>\n'.format(url) +
                '</url>\n'
            )
    with open('dash_docs/assets/sitemap.xml', 'w') as f:
        f.write(
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">\n' +
            '<!-- autogenerated by generate-sitemap.py - do not modify manually -->' +
            sitemap +
            '</urlset>\n'
        )


if __name__ == '__main__':
    generate_sitemap()
